name: Test
on: push
  # pull_request:
  #   paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml' ]
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest 
    timeout-minutes: 5
    steps:
      - run: |
          echo "::error::ERROR"
          echo "::warning::WARNING"
          echo "::notice::NOTICE"

          echo "### Title :rocket: " >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

      # - uses: actions/checkout@4
      # - run: |
      #     docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest