name: Test
on: push
  # pull_request:
  #   paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml' ]
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest 
    timeout-minutes: 5
    steps:
      - run: |
          set -x
          hostname
          date
      # - uses: actions/checkout@4
      # - run: |
      #     docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest