name: Test
on: push
  # pull_request:
  #   paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml' ]
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test1:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: test_1
        run: echo "result=TTEESST" >> "${GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.test_1.outputs.result }}
  test2:
    runs-on: ubuntu-latest
    needs: [test1]
    timeout-minutes: 5
    steps:
      - run: echo ${RESULT}
        env:
          RESULT: ${{ needs.test1.outputs.result }}

  
  # test:
  #   runs-on: ubuntu-latest 
  #   timeout-minutes: 5
  #   steps:
  #     - run: |

  #         echo "::error::ERROR"
  #         echo "::warning::WARNING"
  #         echo "::notice::NOTICE"

  #         echo "### Title :rocket: " >> "${GITHUB_STEP_SUMMARY}"
  #         echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
  #         echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

      # - uses: actions/checkout@4
      # - run: |
      #     docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest